# -*- coding: utf-8 -*-
"""ex1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QoHJA6hH34-VmSfrdpct_POALtVHQZTa
"""

def my_add(a,b):
  return a+b
